class BankRunner{
	public static void main(String[] bank){
		Bank ref = new Bank();
		ref.id = 1;
		ref.name = "AXIS BANK";
		ref.branchName = "BTM LAYOUT";
		ref.ifscCode = "UTIB0001615";
		ref.swiftCode = "SWIFT Code Axis Bank";
		ref.noOfWorker = 6;
		ref.branchManager = "sdfghj";
		System.out.println("Bank details created");
		System.out.println("bank ref id is " +ref.id);
		System.out.println("bank name is " +ref.name);
		System.out.println("bank branchName is " +ref.branchName);
		System.out.println("ifsc code is " +ref.ifscCode);
		System.out.println("swift code is " +ref.swiftCode);
		System.out.println("no of worker present is " +ref.noOfWorker);
		System.out.println("branchManager name is " +ref.branchManager);
		System.out.println("Bank details ended");
		
		Bank ref1 = new Bank();
		ref1.id = 2;
		ref1.name = "BANK OF BARODA (BOB)";
		ref1.branchName = "HAVERI BR-KARNATAKA";
		ref1.ifscCode = "BARB0HAVERI";
		ref1.swiftCode = "SWIFT Code Bank of Baroda (BOB)";
		ref1.noOfWorker = 7;
		ref1.branchManager = "asdfgh";
		System.out.println("Bank details created");
		System.out.println("bank ref id is " +ref1.id);
		System.out.println("bank name is " +ref1.name);
		System.out.println("bank branchName is " +ref1.branchName);
		System.out.println("ifsc code is " +ref1.ifscCode);
		System.out.println("swift code is " +ref1.swiftCode);
		System.out.println("no of worker present is " +ref1.noOfWorker);
		System.out.println("branchManager name is " +ref1.branchManager);
		System.out.println("Bank details ended");
		
		Bank ref2 = new Bank();
		ref2.id = 3;
		ref2.name = "CANARA BANK";
		ref2.branchName = "NAPOKLU";
		ref2.ifscCode = "CNRB0000554";
		ref2.swiftCode = "SWIFT Code Canara Bank";
		ref2.noOfWorker = 5;
		ref2.branchManager = "sdfghj";
		System.out.println("Bank details created");
		System.out.println("bank ref id is " +ref2.id);
		System.out.println("bank name is " +ref2.name);
		System.out.println("bank branchName is " +ref2.branchName);
		System.out.println("ifsc code is " +ref2.ifscCode);
		System.out.println("swift code is " +ref2.swiftCode);
		System.out.println("no of worker present is " +ref2.noOfWorker);
		System.out.println("branchManager name is " +ref2.branchManager);
		System.out.println("Bank details ended");
		
		Bank ref3 = new Bank();
		ref3.id = 4;
		ref3.name = "STATE BANK OF INDIA (SBI)";
		ref3.branchName = "KOTHATHI";
		ref3.ifscCode = "SBIN0040172";
		ref3.swiftCode = "SWIFT Code State Bank of India (SBI)";
		ref3.noOfWorker = 6;
		ref3.branchManager = "sdfghj";
		System.out.println("Bank details created");
		System.out.println("bank ref id is " +ref3.id);
		System.out.println("bank name is " +ref3.name);
		System.out.println("bank branchName is " +ref3.branchName);
		System.out.println("ifsc code is " +ref3.ifscCode);
		System.out.println("swift code is " +ref3.swiftCode);
		System.out.println("no of worker present is " +ref3.noOfWorker);
		System.out.println("branchManager name is " +ref3.branchManager);
		System.out.println("Bank details ended");
		
		Bank ref4 = new Bank();
		ref4.id = 5;
		ref4.name = "HDFC BANK";
		ref4.branchName = "CHANNARAYAPATNA";
		ref4.ifscCode = "HDFC0002998";
		ref4.swiftCode = "SWIFT Code HDFC Bank";
		ref4.noOfWorker = 6;
		ref4.branchManager = "sdfghj";
		System.out.println("Bank details created");
		System.out.println("bank ref id is " +ref4.id);
		System.out.println("bank name is " +ref4.name);
		System.out.println("bank branchName is " +ref4.branchName);
		System.out.println("ifsc code is " +ref4.ifscCode);
		System.out.println("swift code is " +ref4.swiftCode);
		System.out.println("no of worker present is " +ref4.noOfWorker);
		System.out.println("branchManager name is " +ref4.branchManager);
		System.out.println("Bank details ended");
		
		Bank ref5 = new Bank();
		ref5.id = 6;
		ref5.name = "ICICI BANK";
		ref5.branchName = "BANGALORE M-G-ROAD";
		ref5.ifscCode = "ICIC0006561";
		ref5.swiftCode = "SWIFT Code ICICI Bank";
		ref5.noOfWorker = 6;
		ref5.branchManager = "sdfghj";
		System.out.println("Bank details created");
		System.out.println("bank ref id is " +ref5.id);
		System.out.println("bank name is " +ref5.name);
		System.out.println("bank branchName is " +ref5.branchName);
		System.out.println("ifsc code is " +ref5.ifscCode);
		System.out.println("swift code is " +ref5.swiftCode);
		System.out.println("no of worker present is " +ref5.noOfWorker);
		System.out.println("branchManager name is " +ref5.branchManager);
		System.out.println("Bank details ended");
		
		Bank ref6 = new Bank();
		ref6.id = 7;
		ref6.name = "PUNJAB NATIONAL BANK (PNB)";
		ref6.branchName = "KOPPAL";
		ref6.ifscCode = "PUNB0988600";
		ref6.swiftCode = "SWIFT Code Punjab National Bank (PNB)";
		ref6.noOfWorker = 6;
		ref6.branchManager = "sdfghj";
		System.out.println("Bank details created");
		System.out.println("bank ref id is " +ref6.id);
		System.out.println("bank name is " +ref6.name);
		System.out.println("bank branchName is " +ref6.branchName);
		System.out.println("ifsc code is " +ref6.ifscCode);
		System.out.println("swift code is " +ref6.swiftCode);
		System.out.println("no of worker present is " +ref6.noOfWorker);
		System.out.println("branchManager name is " +ref6.branchManager);
		System.out.println("Bank details ended");
		
		Bank ref7 = new Bank();
		ref7.id = 8;
		ref7.name = "UNION BANK OF INDIA";
		ref7.branchName = "DHARWAD";
		ref7.ifscCode = "UBIN0536580";
		ref7.swiftCode = "SWIFT Code Union Bank of India";
		ref7.noOfWorker = 6;
		ref7.branchManager = "sdfghj";
		System.out.println("Bank details created");
		System.out.println("bank ref id is " +ref7.id);
		System.out.println("bank name is " +ref7.name);
		System.out.println("bank branchName is " +ref7.branchName);
		System.out.println("ifsc code is " +ref7.ifscCode);
		System.out.println("swift code is " +ref7.swiftCode);
		System.out.println("no of worker present is " +ref7.noOfWorker);
		System.out.println("branchManager name is " +ref7.branchManager);
		System.out.println("Bank details ended");
	}
}